[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && python -m venv venv && ./venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "rm -rf backend/app/static",
  "mkdir -p backend/app/static",
  "cp -r frontend/dist/* backend/app/static/"
]

[start]
cmd = "cd backend && ./venv/bin/flask --app wsgi.py db upgrade && ./venv/bin/gunicorn wsgi:app --bind 0.0.0.0:$PORT"
